//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManager.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GymManager.Domain.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunos datos introducidos no son válidos..
        /// </summary>
        internal static string AlgunosDatosIntroducidosNoSonValidos {
            get {
                return ResourceManager.GetString("AlgunosDatosIntroducidosNoSonValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento conflicto.
        /// </summary>
        internal static string ElementoConflicto {
            get {
                return ResourceManager.GetString("ElementoConflicto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento ya existe..
        /// </summary>
        internal static string ElementoDuplicado {
            get {
                return ResourceManager.GetString("ElementoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento no encontrado..
        /// </summary>
        internal static string ElementoNoEncontrado {
            get {
                return ResourceManager.GetString("ElementoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en validación de datos.
        /// </summary>
        internal static string ErrorValidacionDatos {
            get {
                return ResourceManager.GetString("ErrorValidacionDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el elemento con identificador {0}..
        /// </summary>
        internal static string NoSeEncontroElementoConId {
            get {
                return ResourceManager.GetString("NoSeEncontroElementoConId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo ejecutar la operación solicitada..
        /// </summary>
        internal static string NoSePudoEjecutarLaOperacionSolicitada {
            get {
                return ResourceManager.GetString("NoSePudoEjecutarLaOperacionSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo obtener la información solicitada..
        /// </summary>
        internal static string NoSePudoObtenerInformacionSolicitada {
            get {
                return ResourceManager.GetString("NoSePudoObtenerInformacionSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de error no válido: {0}.
        /// </summary>
        internal static string TipoErrorNoValido {
            get {
                return ResourceManager.GetString("TipoErrorNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe elemento: {0}.
        /// </summary>
        internal static string YaExisteElementoX {
            get {
                return ResourceManager.GetString("YaExisteElementoX", resourceCulture);
            }
        }
    }
}
